version: '3'


services:
  api:
    build: .
    depends_on:
      - postgres
    command: go run server.go
    entrypoint: ''
    environment:
      - DB_USERNAME=fastpos
      - DB_PASSWORD=fastpos
      - DB_HOST=postgres
      - DB_NAME=fastpos
      - DB_PORT=5432
      # - TELEGRAM_BOT=true
      - TG_TOKEN=
      - ROOT_PASSWORD=password
      - JWT_SECRET=SAFESUPERSAFESECRET
      - GOOGLE_CLIENT_ID=SAFESUPERSAFESECRET
      - R2_BUCKET_NAME=fastpos
      - R2_ACCOUNT_ID=Fake
      - R2_ACCESS_KEY_ID=Fake
      - R2_ACCESS_KEY_SECRET=Fake
    volumes:
      - ./:/usr/src/app
    ports:
      - '8083:8083'
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=fastpos
      - POSTGRES_PASSWORD=fastpos
      - POSTGRES_DB=fastpos
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  # asynqmon:
  #   image: hibiken/asynqmon