apiVersion: apps/v1
kind: Deployment
metadata:  
  name: fastpos-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: lessnoteapi
  template:
    metadata:
      labels:
        component: lessnoteapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: lessnoteapi
          image: timabilov33/lessnoteapi:latest
          # resources:
          #   limits:
          #     cpu: 500M
          #     memory: 512Mi
          ports:
            - containerPort: 8083
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: user
                  name: fastpos-pg-creds
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastpos-pg-creds
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: fastpos-pg-creds
                  key: db
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: fastpos-pg-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: fastpos-pg-creds
                  key: port
            - name: R2_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: fastpos-r2-creds
                  key: bucket
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: fastpos-r2-creds
                  key: account_id
            - name: R2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fastpos-r2-creds
                  key: access_key_id
            - name: R2_ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: fastpos-r2-creds
                  key: access_key_secret
            
---
apiVersion: v1
kind: Service
metadata:
   name: lessnoteapi-cluster-ip-service
spec:
  selector:
    component: lessnoteapi 
  ports:
    - port: 8083
      targetPort: 8083
